name: build image

on:
  push:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Install dependence
        run: |
          sudo apt-get install -y jq curl
          curl -s 'https://registry.hub.docker.com/v1/repositories/jenkins/jenkins/tags' | jq '.[].name' | grep centos7 | tr -d '"' > /tmp/tags
          echo ${{ secrets.ACR_TOKEN }} | docker login --username=${{ secrets.ACR_USERNAME }} --password-stdin registry.cn-shenzhen.aliyuncs.com
          cd ./jenkins
          cat /tmp/tags | while read line
          do
            docker build -t registry.cn-shenzhen.aliyuncs.com/jackops/jenkins:${line}-plugins -f Dockerfile .
            docker images 
          done

      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Login to Aliyun ACR
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: registry.cn-shenzhen.aliyuncs.com
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./jenkins
      #     push: true
      #     tags: |
      #       registry.cn-shenzhen.aliyuncs.com/jackops/jenkins-slave:test

