name: build image

on:
  push:
    branches:
      - '*'
    # 忽略指定文件
    paths-ignore:
    - 'jenkins/jenkins_history.txt'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build Jenkins centos image with plugins
        run: |
          sudo apt-get install -y jq curl
          curl -s 'https://registry.hub.docker.com/v1/repositories/jenkins/jenkins/tags' | jq '.[].name' | grep centos7 | head -3 | tr -d '"' > /tmp/tags
          echo ${{ secrets.ACR_TOKEN }} | docker login --username=${{ secrets.ACR_USERNAME }} --password-stdin registry.cn-shenzhen.aliyuncs.com
          cd ./jenkins
          cat /tmp/tags | while read line
          do
            if [ $(cat jenkins_history.txt | grep ${line} | wc -l) == 0 ];then
              sed "s/IMAGE_TAG/$line/g" ./Dockerfile_template > ./Dockerfile
              docker build -t registry.cn-shenzhen.aliyuncs.com/jackops/jenkins:${line}-plugins -f ./Dockerfile .
              docker push registry.cn-shenzhen.aliyuncs.com/jackops/jenkins:${line}-plugins
              echo ${line} >> jenkins_history.txt
            fi
          done
      - 
        name: Git Commit & Push
        run: |
          git config --global user.email ${{ secrets.GIT_MAIL }}
          git config --global user.name ${{ secrets.GIT_USER }}
          git add .
          git commit -m "Updated at $(date +%Y-%m-%d\ %H:%M:%S)" -a || echo "nothing to commit"
          git push
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Login to Aliyun ACR
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: registry.cn-shenzhen.aliyuncs.com
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./jenkins
      #     push: true
      #     tags: |
      #       registry.cn-shenzhen.aliyuncs.com/jackops/jenkins:test

